// Generated by CoffeeScript 1.7.1
$(function() {
  var compassWatchID, watchHeading, watchHeadingError, watchHeadingSuccess;
  watchHeading = function() {
    var options, _compassWatchID;
    options = {
      frequency: 100
    };
    return _compassWatchID = applican.compass.watchHeading(watchHeadingSuccess, watchHeadingError, options);
  };
  watchHeadingSuccess = function(res) {
    return $(".needle img").css({
      transform: "rotateZ(" + res.magneticHeading + "deg)"
    });
  };
  watchHeadingError = function(e) {
    var dump;
    dump = "watchHeadingError\n";
    dump += "code:" + e.code + "\n";
    return console.error(dump);
  };
  compassWatchID = void 0;
  return watchHeading();
});
